module Tarefa2_2022li1g029_Spec where

import LI12223
import Tarefa2_2022li1g029
import Test.HUnit

testsT2 :: Test
testsT2 = TestLabel "Testes Tarefa 2" $ test [ "Teste 1" ~: estendeMapa (Mapa 4 [(Relva,[Arvore,Nenhum,Arvore,Nenhum]),(Relva,[Nenhum,Nenhum,Nenhum,Nenhum]),(Relva,[Arvore,Nenhum,Nenhum,Nenhum]),(Relva,[Arvore,Nenhum,Nenhum,Nenhum]),(Relva,[Arvore,Arvore,Nenhum,Nenhum])]) 16 ~=? Mapa 4 [(Relva,[Arvore,Nenhum,Arvore,Nenhum]),(Relva,[Nenhum,Nenhum,Nenhum,Nenhum]),(Relva,[Arvore,Nenhum,Nenhum,Nenhum]),(Relva,[Arvore,Nenhum,Nenhum,Nenhum]),(Relva,[Arvore,Arvore,Nenhum,Nenhum]),(Estrada 0,[Nenhum,Carro,Carro,Carro])],
                                               "Teste 2" ~: estendeMapa (Mapa 4 [(Relva,[Arvore,Nenhum,Arvore,Nenhum]),(Relva,[Nenhum,Nenhum,Nenhum,Nenhum]),(Relva,[Arvore,Nenhum,Nenhum,Nenhum]),(Relva,[Arvore,Nenhum,Nenhum,Nenhum]),(Relva,[Arvore,Arvore,Nenhum,Nenhum])]) 17 ~=? Mapa 4 [(Relva,[Arvore,Nenhum,Arvore,Nenhum]),(Relva,[Nenhum,Nenhum,Nenhum,Nenhum]),(Relva,[Arvore,Nenhum,Nenhum,Nenhum]),(Relva,[Arvore,Nenhum,Nenhum,Nenhum]),(Relva,[Arvore,Arvore,Nenhum,Nenhum]),(Rio 0,[Nenhum,Tronco,Nenhum,Nenhum])],
                                               "Teste 3" ~: estendeMapa (Mapa 4 [(Relva,[Arvore,Nenhum,Arvore,Nenhum]),(Relva,[Nenhum,Nenhum,Nenhum,Nenhum]),(Relva,[Arvore,Nenhum,Nenhum,Nenhum]),(Relva,[Arvore,Nenhum,Nenhum,Nenhum]),(Relva,[Arvore,Arvore,Nenhum,Nenhum])]) 18 ~=? Mapa 4 [(Relva,[Arvore,Nenhum,Arvore,Nenhum]),(Relva,[Nenhum,Nenhum,Nenhum,Nenhum]),(Relva,[Arvore,Nenhum,Nenhum,Nenhum]),(Relva,[Arvore,Nenhum,Nenhum,Nenhum]),(Relva,[Arvore,Arvore,Nenhum,Nenhum]),(Estrada 0,[Nenhum,Carro,Carro,Carro])],
                                               "Teste 4" ~: estendeMapa (Mapa 7 [(Rio 1,[Tronco,Nenhum,Tronco,Nenhum,Tronco,Nenhum,Nenhum]),(Rio (-1),[Tronco,Tronco,Tronco,Tronco,Tronco,Nenhum,Nenhum]),(Rio 1,[Tronco,Nenhum,Tronco,Nenhum,Nenhum,Tronco,Nenhum]),(Rio (-1),[Tronco,Nenhum,Tronco,Nenhum,Nenhum,Tronco,Nenhum])]) 24 ~=? Mapa 7 [(Rio 1,[Tronco,Nenhum,Tronco,Nenhum,Tronco,Nenhum,Nenhum]),(Rio (-1),[Tronco,Tronco,Tronco,Tronco,Tronco,Nenhum,Nenhum]),(Rio 1,[Tronco,Nenhum,Tronco,Nenhum,Nenhum,Tronco,Nenhum]),(Rio (-1),[Tronco,Nenhum,Tronco,Nenhum,Nenhum,Tronco,Nenhum]),(Estrada 0,[Nenhum,Carro,Carro,Carro,Nenhum,Carro,Nenhum])],
                                               "Teste 5" ~: estendeMapa (Mapa 7 [(Rio 1,[Tronco,Nenhum,Tronco,Nenhum,Tronco,Nenhum,Nenhum]),(Rio (-1),[Tronco,Tronco,Tronco,Tronco,Tronco,Nenhum,Nenhum]),(Rio 1,[Tronco,Nenhum,Tronco,Nenhum,Nenhum,Tronco,Nenhum]),(Rio (-1),[Tronco,Nenhum,Tronco,Nenhum,Nenhum,Tronco,Nenhum])]) 25 ~=? Mapa 7 [(Rio 1,[Tronco,Nenhum,Tronco,Nenhum,Tronco,Nenhum,Nenhum]),(Rio (-1),[Tronco,Tronco,Tronco,Tronco,Tronco,Nenhum,Nenhum]),(Rio 1,[Tronco,Nenhum,Tronco,Nenhum,Nenhum,Tronco,Nenhum]),(Rio (-1),[Tronco,Nenhum,Tronco,Nenhum,Nenhum,Tronco,Nenhum]),(Relva,[Nenhum,Arvore,Nenhum,Nenhum,Nenhum,Nenhum,Nenhum])],
                                               "Teste 6" ~: estendeMapa (Mapa 7 [(Rio 1,[Tronco,Nenhum,Tronco,Nenhum,Tronco,Nenhum,Nenhum]),(Rio (-1),[Tronco,Tronco,Tronco,Tronco,Tronco,Nenhum,Nenhum]),(Rio 1,[Tronco,Nenhum,Tronco,Nenhum,Nenhum,Tronco,Nenhum]),(Rio (-1),[Tronco,Nenhum,Tronco,Nenhum,Nenhum,Tronco,Nenhum])]) 26 ~=? Mapa 7 [(Rio 1,[Tronco,Nenhum,Tronco,Nenhum,Tronco,Nenhum,Nenhum]),(Rio (-1),[Tronco,Tronco,Tronco,Tronco,Tronco,Nenhum,Nenhum]),(Rio 1,[Tronco,Nenhum,Tronco,Nenhum,Nenhum,Tronco,Nenhum]),(Rio (-1),[Tronco,Nenhum,Tronco,Nenhum,Nenhum,Tronco,Nenhum]),(Estrada 0,[Nenhum,Carro,Carro,Nenhum,Carro,Carro,Nenhum])],
                                               "Teste 7" ~: estendeMapa (Mapa 6 [(Estrada 1,[Carro,Carro,Nenhum,Nenhum,Carro,Carro]),(Estrada (-1),[Carro,Nenhum,Carro,Nenhum,Carro,Carro]),(Estrada 1,[Carro,Nenhum,Nenhum,Nenhum,Carro,Carro]),(Estrada (-1),[Carro,Nenhum,Nenhum,Nenhum,Nenhum,Carro]),(Estrada 1,[Nenhum,Nenhum,Nenhum,Nenhum,Carro,Carro])]) 3 ~=? Mapa 6 [(Estrada 1,[Carro,Carro,Nenhum,Nenhum,Carro,Carro]),(Estrada (-1),[Carro,Nenhum,Carro,Nenhum,Carro,Carro]),(Estrada 1,[Carro,Nenhum,Nenhum,Nenhum,Carro,Carro]),(Estrada (-1),[Carro,Nenhum,Nenhum,Nenhum,Nenhum,Carro]),(Estrada 1,[Nenhum,Nenhum,Nenhum,Nenhum,Carro,Carro]),(Relva,[Nenhum,Arvore,Nenhum,Arvore,Nenhum,Arvore])],
                                               "Teste 8" ~: estendeMapa (Mapa 6 [(Estrada 1,[Carro,Carro,Nenhum,Nenhum,Carro,Carro]),(Estrada (-1),[Carro,Nenhum,Carro,Nenhum,Carro,Carro]),(Estrada 1,[Carro,Nenhum,Nenhum,Nenhum,Carro,Carro]),(Estrada (-1),[Carro,Nenhum,Nenhum,Nenhum,Nenhum,Carro]),(Estrada 1,[Nenhum,Nenhum,Nenhum,Nenhum,Carro,Carro])]) 4 ~=? Mapa 6 [(Estrada 1,[Carro,Carro,Nenhum,Nenhum,Carro,Carro]),(Estrada (-1),[Carro,Nenhum,Carro,Nenhum,Carro,Carro]),(Estrada 1,[Carro,Nenhum,Nenhum,Nenhum,Carro,Carro]),(Estrada (-1),[Carro,Nenhum,Nenhum,Nenhum,Nenhum,Carro]),(Estrada 1,[Nenhum,Nenhum,Nenhum,Nenhum,Carro,Carro]),(Rio 0,[Nenhum,Tronco,Tronco,Tronco,Tronco,Tronco])],
                                               "Teste 9" ~: estendeMapa (Mapa 6 [(Estrada 1,[Carro,Carro,Nenhum,Nenhum,Carro,Carro]),(Estrada (-1),[Carro,Nenhum,Carro,Nenhum,Carro,Carro]),(Estrada 1,[Carro,Nenhum,Nenhum,Nenhum,Carro,Carro]),(Estrada (-1),[Carro,Nenhum,Nenhum,Nenhum,Nenhum,Carro]),(Estrada 1,[Nenhum,Nenhum,Nenhum,Nenhum,Carro,Carro])]) 5 ~=? Mapa 6 [(Estrada 1,[Carro,Carro,Nenhum,Nenhum,Carro,Carro]),(Estrada (-1),[Carro,Nenhum,Carro,Nenhum,Carro,Carro]),(Estrada 1,[Carro,Nenhum,Nenhum,Nenhum,Carro,Carro]),(Estrada (-1),[Carro,Nenhum,Nenhum,Nenhum,Nenhum,Carro]),(Estrada 1,[Nenhum,Nenhum,Nenhum,Nenhum,Carro,Carro]),(Relva,[Nenhum,Arvore,Nenhum,Nenhum,Nenhum,Nenhum])],
                                               "Teste 10" ~: estendeMapa (Mapa 12 [(Rio 1,[Tronco,Tronco,Nenhum,Nenhum,Tronco,Tronco,Nenhum,Nenhum,Nenhum,Tronco,Nenhum,Nenhum]),(Relva,[Arvore,Nenhum,Nenhum,Nenhum,Nenhum,Nenhum,Nenhum,Arvore,Arvore,Arvore,Nenhum,Nenhum])]) 10 ~=? Mapa 12 [(Rio 1,[Tronco,Tronco,Nenhum,Nenhum,Tronco,Tronco,Nenhum,Nenhum,Nenhum,Tronco,Nenhum,Nenhum]),(Relva,[Arvore,Nenhum,Nenhum,Nenhum,Nenhum,Nenhum,Nenhum,Arvore,Arvore,Arvore,Nenhum,Nenhum]),(Rio 0,[Nenhum,Tronco,Tronco,Tronco,Tronco,Nenhum,Nenhum,Nenhum,Nenhum,Nenhum,Nenhum,Nenhum])],
                                               "Teste 11" ~: estendeMapa (Mapa 12 [(Rio 1,[Tronco,Tronco,Nenhum,Nenhum,Tronco,Tronco,Nenhum,Nenhum,Nenhum,Tronco,Nenhum,Nenhum]),(Relva,[Arvore,Nenhum,Nenhum,Nenhum,Nenhum,Nenhum,Nenhum,Arvore,Arvore,Arvore,Nenhum,Nenhum])]) 11 ~=? Mapa 12 [(Rio 1,[Tronco,Tronco,Nenhum,Nenhum,Tronco,Tronco,Nenhum,Nenhum,Nenhum,Tronco,Nenhum,Nenhum]),(Relva,[Arvore,Nenhum,Nenhum,Nenhum,Nenhum,Nenhum,Nenhum,Arvore,Arvore,Arvore,Nenhum,Nenhum]),(Estrada 0,[Nenhum,Carro,Nenhum,Nenhum,Nenhum,Carro,Nenhum,Nenhum,Nenhum,Nenhum,Nenhum,Nenhum])],
                                               "Teste 12" ~: estendeMapa (Mapa 12 [(Rio 1,[Tronco,Tronco,Nenhum,Nenhum,Tronco,Tronco,Nenhum,Nenhum,Nenhum,Tronco,Nenhum,Nenhum]),(Relva,[Arvore,Nenhum,Nenhum,Nenhum,Nenhum,Nenhum,Nenhum,Arvore,Arvore,Arvore,Nenhum,Nenhum])]) 12 ~=? Mapa 12 [(Rio 1,[Tronco,Tronco,Nenhum,Nenhum,Tronco,Tronco,Nenhum,Nenhum,Nenhum,Tronco,Nenhum,Nenhum]),(Relva,[Arvore,Nenhum,Nenhum,Nenhum,Nenhum,Nenhum,Nenhum,Arvore,Arvore,Arvore,Nenhum,Nenhum]),(Relva,[Nenhum,Arvore,Arvore,Arvore,Arvore,Arvore,Arvore,Nenhum,Nenhum,Nenhum,Nenhum,Nenhum])],
                                               "Teste 13" ~: estendeMapa (Mapa 12 [(Rio 1,[Tronco,Tronco,Nenhum,Nenhum,Tronco,Tronco,Nenhum,Nenhum,Nenhum,Tronco,Nenhum,Nenhum]),(Relva,[Arvore,Nenhum,Nenhum,Nenhum,Nenhum,Nenhum,Nenhum,Arvore,Arvore,Arvore,Nenhum,Nenhum])]) 13 ~=? Mapa 12 [(Rio 1,[Tronco,Tronco,Nenhum,Nenhum,Tronco,Tronco,Nenhum,Nenhum,Nenhum,Tronco,Nenhum,Nenhum]),(Relva,[Arvore,Nenhum,Nenhum,Nenhum,Nenhum,Nenhum,Nenhum,Arvore,Arvore,Arvore,Nenhum,Nenhum]),(Rio 0,[Nenhum,Tronco,Nenhum,Nenhum,Nenhum,Nenhum,Nenhum,Tronco,Nenhum,Nenhum,Nenhum,Nenhum])],
                                               "Teste 14" ~: estendeMapa (Mapa 12 [(Rio 1,[Tronco,Tronco,Nenhum,Nenhum,Tronco,Tronco,Nenhum,Nenhum,Nenhum,Tronco,Nenhum,Nenhum]),(Relva,[Arvore,Nenhum,Nenhum,Nenhum,Nenhum,Nenhum,Nenhum,Arvore,Arvore,Arvore,Nenhum,Nenhum])]) 14 ~=? Mapa 12 [(Rio 1,[Tronco,Tronco,Nenhum,Nenhum,Tronco,Tronco,Nenhum,Nenhum,Nenhum,Tronco,Nenhum,Nenhum]),(Relva,[Arvore,Nenhum,Nenhum,Nenhum,Nenhum,Nenhum,Nenhum,Arvore,Arvore,Arvore,Nenhum,Nenhum]),(Estrada 0,[Nenhum,Carro,Carro,Nenhum,Carro,Carro,Nenhum,Carro,Carro,Nenhum,Nenhum,Nenhum])],
                                               "Teste 15" ~: estendeMapa (Mapa 12 [(Rio 1,[Tronco,Tronco,Nenhum,Nenhum,Tronco,Tronco,Nenhum,Nenhum,Nenhum,Tronco,Nenhum,Nenhum]),(Relva,[Arvore,Nenhum,Nenhum,Nenhum,Nenhum,Nenhum,Nenhum,Arvore,Arvore,Arvore,Nenhum,Nenhum])]) 15 ~=? Mapa 12 [(Rio 1,[Tronco,Tronco,Nenhum,Nenhum,Tronco,Tronco,Nenhum,Nenhum,Nenhum,Tronco,Nenhum,Nenhum]),(Relva,[Arvore,Nenhum,Nenhum,Nenhum,Nenhum,Nenhum,Nenhum,Arvore,Arvore,Arvore,Nenhum,Nenhum]),(Relva,[Nenhum,Arvore,Nenhum,Arvore,Nenhum,Nenhum,Nenhum,Arvore,Nenhum,Arvore,Nenhum,Nenhum])] ]
